# Generated by Django 3.1.6 on 2021-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210521_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('flavour', models.TextField()),
            ],
        ),
    ]
