# Generated by Django 3.1.6 on 2021-05-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='flavors',
        ),
    ]
