# Generated by Django 3.1.6 on 2021-05-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210524_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavors',
            old_name='name',
            new_name='name1',
        ),
    ]
