# Generated by Django 3.1.6 on 2021-05-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210524_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavors',
            old_name='name1',
            new_name='name',
        ),
    ]
